# Generated by Django 5.1.6 on 2025-05-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitais',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitais',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
