# Generated by Django 5.1.6 on 2025-05-17 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hospitais_latitude_hospitais_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='estrelas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospitais'),
        ),
    ]
