# Generated by Django 5.1.6 on 2025-05-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_comentario_estrelas_alter_comentario_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='estrelas',
            field=models.IntegerField(),
        ),
    ]
