# Generated by Django 5.1.6 on 2025-05-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comentario_estrelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitais',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='hospitais/'),
        ),
    ]
